services:
  scraper:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - sqlserver

  detail_scraper:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - sqlserver
    command: python scraper/detail_scraper.py

  jupyter:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./models:/app/models
    ports:
      - "8888:8888"
    depends_on:
      - sqlserver
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
  api:
    build: .
    env_file: .env
    volumes:
      - ./models:/app/models
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - sqlserver
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: